config/routes.rb
ServiceDesign::Application.routes.draw do
  resources :positions do
    match :save, :on => :collection # :on => :member
  end

  match "access/login"

  get "access/logout"

  resources :sessions do
    get :active_sessions, :on => :collection
    get :active_receiver_asked, :on => :collection
    get :active_owner_answered, :on => :collection
    get :active_owner_asked, :on => :collection
    get :show_active, :on => :collection
    get :passiv_all, :on => :collection
    put :message_read, :on => :member
    get :delete_session, :on => :member
  end

  resources :messages do
    get :send_message, :on => :member
    get :show_active, :on => :collection
    
  end

  resources :users
  
  root :to => 'sessions#passiv_all'

end

app/models/position.rb
class Position < ActiveRecord::Base
  attr_accessible :accuracy, :altitude, :altitude_accuracy, :lat, :long, :timestamp, :user_id
  
  
  belongs_to :user
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController

  # GET /positions
  # GET /positions.json
  def index
    if is_admin?
      @positions = Position.all
    else
      @positions = current_user.positions
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @positions }
    end
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
    @position = Position.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/new
  # GET /positions/new.json
  def new
    @position = Position.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @position }
    end
  end

  # GET /positions/1/edit
  def edit
    @position = Position.find(params[:id])
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(params[:position])

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render json: @position, status: :created, location: @position }
      else
        format.html { render action: "new" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /positions/1
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])

    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url }
      format.json { head :no_content }
    end
  end

  def save
    unless request.post?

      respond_to do |format|
        format.html { render action: "save" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
        format.mobile do
          render :action => 'save', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    else
      @position = Position.new(:user_id => @current_user.id, :lat => params[:coords][ :latitude ], :long => params[:coords][ :longitude ], :altitude => params[:coords][ :altitude ], :accuracy => params[:coords][ :accuracy ], :altitude_accuracy => params[:coords][ :altitude_accuracy ], :timestamp => params[ :timestamp ])
      logger.debug "-- params[ :timestamp]:#{params[ :timestamp ]}"
      @position.save
      respond_to do |format|
        format.html { render action: "save" }
        format.json { render json: @session.errors, status: :unprocessable_entity }
        format.mobile do
          render :action => 'save', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    #redirect_to position_path(@position)
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :altitude %><br />
    <%= f.text_field :altitude %>
  </div>
  <div class="field">
    <%= f.label :accuracy %><br />
    <%= f.text_field :accuracy %>
  </div>
  <div class="field">
    <%= f.label :altitude_accuracy %><br />
    <%= f.text_field :altitude_accuracy %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br />
    <%= f.datetime_select :timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Listing positions</h1>

<table>
  <tr>
    <th>User</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Altitude</th>
    <th>Accuracy</th>
    <th>Altitude accuracy</th>
    <th>Timestamp</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @positions.each do |position| %>
  <tr>
    <td><%= position.user_id %></td>
    <td><%= position.lat %></td>
    <td><%= position.long %></td>
    <td><%= position.altitude %></td>
    <td><%= position.accuracy %></td>
    <td><%= position.altitude_accuracy %></td>
    <td><%= position.timestamp %></td>
    <td><%= link_to 'Show', position %></td>
    <td><%= link_to 'Edit', edit_position_path(position) %></td>
    <td><%= link_to 'Destroy', position, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Position', new_position_path %>

<%= link_to 'Save Current Position', save_positions_path %>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @position.user_id %>
</p>

<p>
  <b>Lat:</b>
  <%= @position.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @position.long %>
</p>

<p>
  <b>Altitude:</b>
  <%= @position.altitude %>
</p>

<p>
  <b>Accuracy:</b>
  <%= @position.accuracy %>
</p>

<p>
  <b>Altitude accuracy:</b>
  <%= @position.altitude_accuracy %>
</p>

<p>
  <b>Timestamp:</b>
  <%= @position.timestamp %>
</p>


<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>