config/routes.rb
ServiceDesign::Application.routes.draw do
  resources :positions do
    match :save, :on => :collection # :on => :member
  end

  match "access/login"

  get "access/logout"

  resources :sessions do
    get :active_sessions, :on => :collection
    get :active_receiver_asked, :on => :collection
    get :active_owner_answered, :on => :collection
    get :active_owner_asked, :on => :collection
    get :show_active, :on => :collection
    get :passiv_all, :on => :collection
    put :message_read, :on => :member
    get :delete_session, :on => :member
  end

  resources :messages do
    get :send_message, :on => :member
    get :show_active, :on => :collection
    
  end

  resources :users
  
  root :to => 'sessions#passiv_all'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password_digest, :admin
  #has_secure_password
  #validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, uniqueness: true
   
  has_many :messages
  has_many :sessions, :foreign_key => 'owner_id'
  has_many :positions
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    #only show user list when user is admin
    if is_admin?
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
        format.mobile do
          render :action => 'index', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    else
      redirect_to user_path(current_user)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    #checks if user is admin or if actual_user is the same as the profile that will be shown
    if is_admin? || current_user == @user
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
        format.mobile do
          render :action => 'show', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    else
      redirect_to user_path(current_user)
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      format.mobile do
        render :action => 'new', :formats => 'html', :layout => 'application.mobile.erb'
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
      format.mobile do
        render :action => 'edit', :formats => 'html', :layout => 'application.mobile.erb'
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
        format.mobile { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.mobile do
          render :action => 'new', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
        format.mobile { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.mobile do
          render :action => 'edit', :formats => 'html', :layout => 'application.mobile.erb'
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
      format.mobile { redirect_to users_url }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <% if is_admin? %>
   <div class="admin">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
  	<th>ID</th>
    <th>Email</th>
    <th>Password</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
  	<td><%= user.id %></td>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
     <td><%= user.admin %></td>
     
     
     <% if is_admin? %>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
    <% else %>
    <th></th>
    <th></th>
    <th></th>
    <%end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice">
	<%= notice %>
</p>

<p>
	<b>ID:</b>
	<%= @user.id %>
</p>

<p>
	<b>Email:</b>
	<%= @user.email %>
</p>

<p>
	<b>Password:</b>
	<%= @user.password_digest %>
</p>
<% if is_admin? %>
<p>
	<b>admin:</b>
	<%= @user.admin %>
</p>
<%= link_to 'Show Positions', '#positions', id:'position_toggle' %>
<div class="positions" style="display: none">
	<table>

		<% @user.positions.each do |position| %>

		<tr>
			<td><%= position.user_id %></td>
			<td><%= position.lat %></td>
			<td><%= position.long %></td>
			<td><%= position.altitude %></td>
			<td><%= position.accuracy %></td>
			<td><%= position.altitude_accuracy %></td>
			<td><%= position.timestamp %></td>
			<td><%= link_to 'Show', position %></td>
			<td><%= link_to 'Edit', edit_position_path(position) %></td>
			<td><%= link_to 'Destroy', position, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
		<%end%>
	</table>
</div>
<br />
<%= link_to 'Show Sessions', '#sessions', id:'session_toggle' %>
<div class="sessions" style="display: none">
	<table>

		<% @user.sessions.each do |session| %>

		<tr>
			<td><%= session.owner_id %></td>
			<td><%= session.timeout %></td>
			<td><%= session.forwarding_time %></td>
			<td><%= link_to 'Show', session %></td>
			<td><%= link_to 'Edit', edit_session_path(session) %></td>
			<td><%= link_to 'Destroy', session, confirm: 'Are you sure?', method: :delete %></td>
		</tr>
		</tr>
		<%end%>
	</table>
</div>
<br />
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.mobile.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @user.id %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password_digest %>
</p>
<% if is_admin? %>
<p>
  <b>admin:</b>
  <%= @user.admin %>
</p>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>