config/routes.rb
ServiceDesign::Application.routes.draw do
  resources :positions do
    match :save, :on => :collection # :on => :member
  end

  match "access/login"

  get "access/logout"

  resources :sessions do
    get :active_sessions, :on => :collection
    get :active_receiver_asked, :on => :collection
    get :active_owner_answered, :on => :collection
    get :active_owner_asked, :on => :collection
    get :show_active, :on => :collection
    get :passiv_all, :on => :collection
    put :message_read, :on => :member
    get :delete_session, :on => :member
  end

  resources :messages do
    get :send_message, :on => :member
    get :show_active, :on => :collection
    
  end

  resources :users
  
  root :to => 'sessions#passiv_all'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ServiceDesign</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<link rel="apple-touch-icon" href="/assets/apple-touch-icon-57x57.png" />
		<%= stylesheet_link_tag    "mobile", :media => "all" %>
		<style type="text/css">
			@font-face {
				font-family: 'Conv_FairfieldLTStd-LightItalic';
				src: url('<%= asset_path('FairfieldLTStd-LightItalic.ttf')%>');
				font-weight: normal;
				font-style: normal;
			}
			@font-face {
				font-family: 'Conv_UniversLTStd-Cn';
				src: url('<%= asset_path('UniversLTStd-Cn.ttf')%>');
				font-weight: normal;
				font-style: normal;
			}
		</style>
		<%= csrf_meta_tags %>

	</head>
	<body>
		<div class="w980">
			<div id="navi">
				<% unless @current_user.blank?%>
				<% if is_admin? %>
				<%= link_to 'Profile', users_path, :remote => true, :id => "ajax_trigger"%>
				<% else %>
				<%= link_to 'Profile', user_path(@current_user), :remote => true, :id => "ajax_trigger"%>
				<% end %>
				<%= link_to 'Sessions', active_sessions_sessions_path%>
				<%= link_to 'new Message', new_session_path, :remote => true, :id => "ajax_trigger"%>
				<%= link_to 'logout', access_logout_path, :remote => true, :id => "ajax_trigger"%>
				<%= yield :navi %>
				<% end %>

			</div>
			<div id="content">
				<%= yield %>

			</div>

		</div>
	</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
	<head>
		<title>ServiceDesign</title>

		<meta name="viewport" content="width=device-width, maximum-scale=1.0, user-scalable=0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		<link rel="apple-touch-icon" href="/assets/apple-touch-icon-57x57.png" />

		<%= stylesheet_link_tag    "mobile", :media => "all" %>
		<style type="text/css">
		@font-face {
			font-family: 'Conv_FairfieldLTStd-LightItalic';
			src: url('<%= asset_path('FairfieldLTStd-LightItalic.ttf')%>');
			font-weight: normal;
			font-style: normal;
		}
		@font-face {
			font-family: 'Conv_UniversLTStd-Cn';
			src: url('<%= asset_path('UniversLTStd-Cn.ttf')%>');
			font-weight: normal;
			font-style: normal;
		}
		</style>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	
	</head>
	<body>
		<div class="w980">

			<div id="content">
				<%= yield %>
			</div>
			<div id="navi" style="display:none">
				<% unless @current_user.blank?%>
				<% if is_admin? %>
				<%= link_to 'Profile', users_path,:remote => true, :id => "ajax_trigger"%>
				<% else %>
				<%= link_to 'Profile', user_path(@current_user),:remote => true, :id => "ajax_trigger" %>
				<% end %>
				<%= link_to 'Sessions', active_sessions_sessions_path%>
				<%= link_to 'new Message', new_session_path, :remote => true, :id => "ajax_trigger" %>
				<%= link_to 'logout', access_logout_path, :remote => true, :id => "ajax_trigger"%>
				<%= yield :navi %>
				<% end %>

			</div>
		</div>
	</body>
</html>